
class Signal:

  FAILED = 0
  SUCCEED = 1
  ENABLE_BUTTON_START = 2
  ENABLE_BUTTON_TEST = 3
  AUDIO_FINISHED = 4
  UPDATE_INFO_LABELS = 5
  DISABLE_COMBOBOXES = 6
  ENABLE_COMBOBOXES = 7
  UPDATE_PROGRESS_LABEL = 8
  UPDATE_FAIL_WORDS = 9
  DOWNLOAD_FINSISHED = 10

